import dep -> deplib;
import testlib -> *;

enum Weather {
    SUNNY = 1,
    CLOUDY = 2,
    RAINY = 4,
    SNOWY = 8,
    THUNDER = 16,
    WINDY = 32,
    STORMY = deplib.STORMY64,

    FOG = 128,
    THUNDERSTORMS = Weather.THUNDER | Weather.RAINY | Weather.WINDY,
    BLIZZARD = Weather.WINDY | Weather.SNOWY,
    RAIN_SNOW_MIX = Weather.SNOWY | Weather.RAINY,
}

function isRainy(weatherMask) {
    return (weatherMask & Weather.RAINY) != 0;
}

function main(args) {
    assertStrEqual(0 | Weather.SUNNY, 1);

    // TODO: uncomment these when enum serialization is supported.
    // assertStrEqual(Weather.SUNNY * 1, 1);
    // assertStrEqual(Weather.SUNNY + '', 'SUNNY');

    // FAILING TEST
    assertStrEqual(isRainy(0 | Weather.SNOWY), false);
    assertStrEqual(isRainy(0 | Weather.SUNNY), false);
    assertStrEqual(isRainy(0 | Weather.RAIN_SNOW_MIX), true);

    assertStrEqual(deplib.LIFE_UNIVERSE_EVERYTHING, 42);

    print("ALL DONE");
}
