import testlib -> *;
import resources;

function main(args) {

    mod = resources.getCurrentResourceModule();
    t = resources.readTextResourceAsString(mod, 'textfile1.txt');
    assertStrEqual(t.trim(), "I am a text file.");

    arr = resources.listAllResources(mod);
    assertStrEqual(
        arr.join("|"),
        "files/flea.png|files/testfile2.txt|resources.config|textfile1.txt");

    img = resources.readImageResource(mod, 'files/flea.png');
    assertStrEqual(img.width + ' x ' + img.height, '64 x 64');

    print("ALL DONE");
}
