
// Compares the stringified-value of each value and prints an error if they don't match.
@public 
function assertStrEqual(a, b) {
    if (a + '' != b + '') {
        print("ERR: " + a + " is not the same as " + b + "!");
    }
}

// Compares two floating point decimals with a bit of fuzzy tolerance.
@public
function assertFloatEqual(expected, actual) {
    diff = expected - actual;
    diff = diff < 0 ? -diff : diff;
    if (diff > 0.000000001) {
        assertStrEqual(expected, actual); // fail
    }
}
