import testlib -> *;
import xml;

function main(args) {
    basicTest();
    assertStrEqual(getXmlErr('<a></a>a'), 'XML Parse Error: Unexpected data at end of root element.');
    entityTest();

    print("ALL DONE");
}

function entityTest() {
    doc = xml.parseXml('
        <a prop="value &lt; &gt; &quot; &apos; &amp; < > &">
            TODO: entities as text nodes.
        </a>
    ');
    assertStrEqual(doc.attributes['prop'], 'value < > " \' & < > &');
}

function basicTest() {
    doc = xml.parseXml('<a attr1="123" attr2="456">Text 1<b>Hello</b>Text 2</a>');
    assertStrEqual(doc.name, 'a');
    assertStrEqual(doc.children.length, 3);
    assertStrEqual(doc.children[0].value, 'Text 1');
    assertStrEqual(doc.attributes['attr1'], '123');
    assertStrEqual(doc.attributes['attr2'], '456');
    assertStrEqual(doc.children[1].name, 'b');
    assertStrEqual(doc.children[1].children.length, 1);
    assertStrEqual(doc.children[1].children[0].value, 'Hello');
    assertStrEqual(doc.children[2].value, 'Text 2');
}

function getXmlErr(str) {
    err = 'NO ERROR!!';
    try {
        xml.parseXml(str);
    } catch (ex) {
        err = ex.message;
    }
    return err;
}