import dep -> deplib;
import testlib -> *;

namespace Internal {
    function memberFunction() {
        return "wheeeeee";
    }
}

function main(args) {
    value = Internal.memberFunction();
    assertStrEqual("wheeeeee", value);

    value = deplib.Internal2.memberFunction2();
    assertStrEqual("wheeeeee2", value);

    value = deplib.notWrappedMember();
    assertStrEqual("bananas", value);

    value = deplib.Deep.Nesting.doubleWrap();
    assertStrEqual("deeeeeep", value);

    print('ALL DONE');
}
