import math;
import testlib -> *;

function main(args) {
    runTest();
}

function runTest() {

    assertFloatEqual(0.8414709848078965, math.sin(1));
    assertFloatEqual(0.5403023058681398, math.cos(1));
    assertFloatEqual(1.5574077246549023, math.tan(1));
    assertFloatEqual(0.5235987755982989, math.arcsin(.5));
    assertFloatEqual(1.0471975511965979, math.arccos(.5));
    assertFloatEqual(0.4636476090008061, math.arctan(.5));
    assertFloatEqual(0.4636476090008061, math.arctan(.5, 1));
    assertFloatEqual(0.4636476090008061, math.arctan(1, 2));
    assertFloatEqual(0.9542425094393249, math.log10(9));
    assertFloatEqual(3.1699250014423126, math.log2(9));
    assertFloatEqual(2.1972245773362196, math.ln(9));
    assertFloatEqual(3.0, math.sqrt(9));
    assertFloatEqual(3.1622776601683795, math.sqrt(10));

    assertStrEqual(1, math.sign(9));
    assertStrEqual(-1, math.sign(-9));
    assertStrEqual(0, math.sign(0));
    assertStrEqual(0, math.abs(0));
    assertStrEqual(3, math.abs(-3));
    assertStrEqual(3, math.abs(3));
    print('ALL DONE');
}
